group:
# Global files to be synced
  - files:
      - source: .github/CODEOWNERS
        dest: .github/CODEOWNERS
      - source: .github/FUNDING.yml
        dest: .github/FUNDING.yml
      - source: .github/dependabot.yml
        dest: .github/dependabot.yml
      - source: .github/labels.yml
        dest: .github/labels.yml
      - source: .github/workflows/create-labels.yml
        dest: .github/workflows/create-labels.yml
      - source: .github/workflows/release.yml
        dest: .github/workflows/release.yml
      - source: .github/auto-merge.yml
        dest: .github/auto-merge.yml
      - source: .github/workflows/auto-merge.yml
        dest: .github/workflows/auto-merge.yml
      - source: .gitignore
        dest: .gitignore
      - LICENSE
      - favicon.ico
      - source: .packager/
        dest: .packager/
    repos: |
        AdiBags_Bears_Alchemy
        AdiBags_Bears_Battle_Pet_Items
        AdiBags_Bears_Blacksmithing
        AdiBags_Bears_Cooking
        AdiBags_Bears_Enchanting
        AdiBags_Bears_Engineering
        AdiBags_Bears_Fishing
        AdiBags-Bears-Fishing-Items
        AdiBags_Bears_Hearthstones
        AdiBags_Bears_Herbs
        AdiBags_Bears_Inscription
        AdiBags_Bears_Jewelcrafting
        AdiBags_Bears_Keystones
        AdiBags_Bears_Leatherworking
        AdiBags_Bears_Mining
        AdiBags_Queens_Conservatory
        AdiBags_Bears_Tailoring
        AdiBags_Bears_Ultimate
        Bears_audio_switcher
        wowAddonTemplate

# only for AdiBags
  - files:
     - source: wow/core.lua
       dest: core.lua
     - source: wow/expansion.lua
       dest: expansion.lua
    repos: |
        AdiBags_Bears_Alchemy
        AdiBags_Bears_Battle_Pet_Items
        AdiBags_Bears_Blacksmithing
        AdiBags_Bears_Cooking
        AdiBags_Bears_Enchanting
        AdiBags_Bears_Engineering
        AdiBags_Bears_Fishing
        AdiBags-Bears-Fishing-Items
        AdiBags_Bears_Hearthstones
        AdiBags_Bears_Herbs
        AdiBags_Bears_Inscription
        AdiBags_Bears_Jewelcrafting
        AdiBags_Bears_Keystones
        AdiBags_Bears_Leatherworking
        AdiBags_Bears_Mining
        AdiBags_Queens_Conservatory
        AdiBags_Bears_Tailoring
        AdiBags_Bears_Ultimate
        wowAddonTemplate

    # only for Professions databases
  - files:
        - source: wow/DF-Global.lua
          dest: DF-Global.lua
        - source: wow/Global-dbs.lua
          dest: Global-dbs.lua
    repos: |
        AdiBags_Bears_Alchemy
        AdiBags_Bears_Blacksmithing
        AdiBags_Bears_Cooking
        AdiBags_Bears_Enchanting
        AdiBags_Bears_Engineering
        AdiBags_Bears_Fishing
        AdiBags_Bears_Herbs
        AdiBags_Bears_Inscription
        AdiBags_Bears_Jewelcrafting
        AdiBags_Bears_Leatherworking
        AdiBags_Bears_Mining
        AdiBags_Bears_Tailoring
        AdiBags_Bears_Ultimate
