group:
# Global files to be synced
  - files:
      - source: .github/CODEOWNERS
        dest: .github/CODEOWNERS
      - source: .github/FUNDING.yml
        dest: .github/FUNDING.yml
      - source: .github/dependabot.yml
        dest: .github/dependabot.yml
      - source: .github/labels.yml
        dest: .github/labels.yml
      - source: .github/workflows/create-labels.yml
        dest: .github/workflows/create-labels.yml
      - source: .github/workflows/release.yml
        dest: .github/workflows/release.yml
      - source: .github/auto-merge.yml
        dest: .github/auto-merge.yml
      - source: .github/workflows/auto-merge.yml
        dest: .github/workflows/auto-merge.yml
      - source: .gitignore
        dest: .gitignore
      - LICENSE
      - favicon.ico
      - source: .packager/
        dest: .packager/
    repos: |
        N6REJ/Adibags_Bears_Alchemy
        N6REJ/AdiBags_Bears_Battle_Pet_Items
        N6REJ/AdiBags_Bears_Blacksmithing
        N6REJ/AdiBags_Bears_Cooking
        N6REJ/Adibags_Bears_Enchanting
        N6REJ/AdiBags_Bears_Engineering
        N6REJ/Adibags_Bears_Fishing
        N6REJ/AdiBags-Bears-Fishing-Items
        N6REJ/AdiBags_Bears_Hearthstones
        N6REJ/AdiBags_Bears_Herbs
        N6REJ/AdiBags_Bears_Inscription
        N6REJ/Adibags_Bears_Jewelcrafting
        N6REJ/AdiBags_Bears_Keystones
        N6REJ/AdiBags_Bears_Leatherworking
        N6REJ/AdiBags_Bears_Mining
        N6REJ/AdiBags_Queens_Conservatory
        N6REJ/AdiBags_Bears_Tailoring
        N6REJ/AdiBags_Bears_Ultimate
        N6REJ/Bears_audio_switcher

# only for Adibags
  - files:
     - source: wow/core.lua
       dest: core.lua
     - source: wow/expansion.lua
       dest: expansion.lua
     - source: wow/DF-Global.lua
       dest: DF-Global.lua
     - source: wow/DF-Elemental.lua
       dest: DF-Elemental.lua
     - source: wow/Global-dbs.lua
       dest: Global-dbs.lua
    repos: |
        N6REJ/Adibags_Bears_Alchemy
        N6REJ/AdiBags_Bears_Blacksmithing
        N6REJ/AdiBags_Bears_Cooking
        N6REJ/Adibags_Bears_Enchanting
        N6REJ/AdiBags_Bears_Engineering
        N6REJ/Adibags_Bears_Fishing
        N6REJ/AdiBags_Bears_Herbs
        N6REJ/AdiBags_Bears_Inscription
        N6REJ/Adibags_Bears_Jewelcrafting
        N6REJ/AdiBags_Bears_Leatherworking
        N6REJ/AdiBags_Bears_Mining
        N6REJ/AdiBags_Bears_Tailoring
        N6REJ/AdiBags_Bears_Ultimate
