name: Sync fiverr Files

on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.5.2

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          SKIP_PR: true

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Create or update tag in child repositories
        env:
          CHILD_REPOS: |
            AdiBags_Bears_Alchemy
            AdiBags_Bears_Battle_Pet_Items
            AdiBags_Bears_Blacksmithing
            AdiBags_Bears_Cooking
            AdiBags_Bears_Enchanting
            AdiBags_Bears_Engineering
            AdiBags_Bears_Fishing
            AdiBags-Bears-Fishing-Items
            AdiBags_Bears_Hearthstones
            AdiBags_Bears_Herbs
            AdiBags_Bears_Inscription
            AdiBags_Bears_Jewelcrafting
            AdiBags_Bears_Keystones
            AdiBags_Bears_Leatherworking
            AdiBags_Bears_Mining
            AdiBags_Queens_Conservatory
            AdiBags_Bears_Tailoring
            AdiBags_Bears_Ultimate
            Bears_audio_switcher
            wowAddonTemplate
        run: |
          for repo in $CHILD_REPOS; do
            if [ -d "$repo" ]; then
              cd "$repo"
              git fetch --tags
              tag=$(git tag --points-at HEAD --list "*.${{ steps.timestamp.outputs.timestamp }}*")
              if [[ -n "$tag" ]]; then
                # Tag already exists, update it
                new_tag="$tag.N"
                git tag "$new_tag" -f
                git push origin "$new_tag" -f
              else
                # Tag doesn't exist, create a new one
                new_tag="${{ steps.timestamp.outputs.timestamp }}"
                git tag "$new_tag"
                git push origin "$new_tag"
              fi
              cd ..
            else
              echo "Child repository directory '$repo' does not exist."
            fi
          done
